### ISSUE TITLE
The disk could not be ejected. Close any programs...

### ISSUE THREAD

**Issue by lexterror** [bgbennyboy/USB-Disk-Ejector#8]
I'm using "USB Disk Ejector 1.3.0.5" and I can't eject my external "WD Passport 1GB" usb drive...
I keep getting the same message and I'm pretty sure I don't have any programs running from my external HDD.

**Comment by ronaldhoek** [comment]
Did you try to use the regular 'Windows' 'Remove hardware' option?

**Comment by lexterror** [comment]
That option is not available for this device (WD Passport 1TB external HDD)

**Comment by ronaldhoek** [comment]
Hhmm, not even in the device menu? I've never seen USB-devices, which using caching, to not show this option.

Example: A USB DVD-drive wont show this option, because it is not necessary. And an USB-drive wtih caching disable, does not need this option too...

Did you try to inspect usage of the files on the drive by tools like 'Unlocker' by any chance?

**Comment by lexterror** [comment]
Thanks for being patient. I'm trying to restore the "Safely Remove Hardware" icon, but I can't find a way to do so. I'm using Windows 10.

**Comment by ronaldhoek** [comment]
Not sure how to do that... But you can try the 'device' menu and right click your WD Passport device there. Maybe is has the 'Remove hardware' option... I'm not using Win10 so I don't know the correct menu's.

**Comment by lexterror** [comment]
Turns out I had a bad Windows Installation. "USB Disk Ejector" works great now. Thanks!
